### ISSUE TITLE
Translating deck to Traditional Chainese

### ISSUE THREAD

**Issue by KnowScratcher** [anki-geo/ultimate-geography#655]
Hello, I would like to translate this deck into Traditional Chinese because some transitions in Simplified Chinese don't work in regions using Traditional Chinese.

One main question is, according to the CONTRIBUTING.md 
> In most cases, the language code should match the Wikipedia subdomain for that language
There's already Simplified Chinese occupying the code "ZH", what should I put for the language code?

Another question is that the encoding of the files is unknown or unrecognized for Excel, how can I open and edit it?

Please let me know if there's more for me to keep in mind while translating.

Thanks.

**Comment by ukanuk** [comment]
I do not know the right answer. But https://en.wikipedia.org/wiki/List_of_Wikipedias and also https://meta.wikimedia.org/wiki/Wikipedias_in_multiple_writing_systems show that some options could be: 
```
zh-hans, zh-hant, zh-cn, zh-hk, zh-mo, zh-my, zh-sg, zh-tw
```

More information appears to be in https://zh.wikipedia.org/wiki/Wikipedia:%E5%AD%97%E8%AF%8D%E8%BD%AC%E6%8D%A2, but I cannot read that. 

Ultimately _you_ might be the right person to make this decision, as you may have more information than us. And, it's not a very big deal anyway. Something as simple as `zh1` and `zh2` would still fulfill 99% of the needs of a translation; it would just be a tad harder for users studying Chinese to figure out which deck version they should use and edit.

As for your issue with Excel, maybe one of the other translators will be able to share what they did.

**Comment by ruin1990** [comment]
Traditional Chinese has subtle differences in many regions. You can first translate it to see if there are any differences in corresponding characters, because 1% of the characters are different.
If this happens, wouldn't it be better to differentiate by region?

**Comment by KnowScratcher** [comment]
> Traditional Chinese has subtle differences in many regions. You can first translate it to see if there are any differences in corresponding characters, because 1% of the characters are different. If this happens, wouldn't it be better to differentiate by region?

I see your point, and I must clarify that the translation I meant was Traditional Chinese for Taiwan. I've noted it as "zh-tw" as most websites do. By the way, Simplified Chinese and Traditional Chinese(Taiwan) have many different characters and even different translations, which is one reason I wanted to translate them into Traditional Chinese.

**Comment by aplaice** [comment]
@KnowScratcher thanks very much for offering to contribute a translation!  It's greatly appreciated!


Regarding the language code I agree with @ukanuk and @ruin1990 (btw thanks for your comments!) that using something like `zh-cn` and `zh-tw` for the two translations would be a sensible solution.  (`zh-hans` and `zh-hant` is also an option, but probably worse for the reasons noted by @ruin1990.)

<hr/>

However, first, is it the case the current Simplified Chinese translation is not easily usable for people accustomed purely to Traditional characters?  I expect the answer is no, it's not easily usable for everybody, but I'd just like to make sure before you do a lot of work!

(If it is easily usable (people learning from the deck won't be confused and/or significantly slowed down (e.g. "translating" all the characters on the go)), then I'm not certain that we would want a Traditional Chinese version, since every translation adds overhead for later expansion of the deck.  For comparison, we don't have an US English version, even though it might be nice to have, since the version with British English is perfectly comprehensible to people from the US.  However, a different set of characters is clearly a greater difference than minor spelling changes and slightly different preferred vocabulary.)



<hr/>

> Another question is that the encoding of the files is unknown or unrecognized for Excel, how can I open and edit it?

Unfortunately, I have little experience with character encodings and locales, especially on Windows(?).  The files are UTF-8 encoded which should be readable/importable everywhere.

Maybe if you provide more info on Excel/OS version and system locale somebody else could provide suggestions?

<hr/>

Thanks again!

**Comment by axelboc** [comment]
We've ran into this Excel issue before. Excel just [doesn't like](https://theonemanitdepartment.wordpress.com/2014/12/15/the-absolute-minimum-everyone-working-with-data-absolutely-positively-must-know-about-file-types-encoding-delimiters-and-data-types-no-excuses/) UTF-8-encoded CSV files, sadly. 😢 I'd recommend using another program or even an online CSV editor.

**Comment by KnowScratcher** [comment]
@aplaice 

> However, first, is it the case the current Simplified Chinese translation is not easily usable for people accustomed purely to Traditional characters? I expect the answer is no, it's not easily usable for everybody, but I'd just like to make sure before you do a lot of work!

Thanks for noticing me. I've made sure that there will be many differences between these two languages and that the Simplified Chinese translation is not easily usable for people accustomed purely to Traditional characters. Thus, I would continue to translate this project.

**Comment by aplaice** [comment]
Great! Thanks for checking! I hope you've resolved or managed to work around the encoding issues!

**Comment by KnowScratcher** [comment]
Hi, does anyone here met this error message before?
```txt
INFO:root:Builder file recipes/source_to_anki.yaml is ✔ good
INFO:root:Attempting to generate Guids
INFO:root:Generate guids complete
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\.virtualenvs\ultimate-geography-Xfb4eIRA\Scripts\brain_brew.EXE\__main__.py", line 7, in <module>
  File "C:\Users\user\.virtualenvs\ultimate-geography-Xfb4eIRA\lib\site-packages\brain_brew\main.py", line 19, in main
    command.execute()
  File "C:\Users\user\.virtualenvs\ultimate-geography-Xfb4eIRA\lib\site-packages\brain_brew\commands\run_recipe\run_recipe.py", line 15, in execute
    recipe = TopLevelBuilder.parse_and_read(self.recipe_file_name, self.verify_only)
  File "C:\Users\user\.virtualenvs\ultimate-geography-Xfb4eIRA\lib\site-packages\brain_brew\commands\run_recipe\top_level_builder.py", line 60, in parse_and_read
    return cls.from_list(recipe_data)
  File "C:\Users\user\.virtualenvs\ultimate-geography-Xfb4eIRA\lib\site-packages\brain_brew\commands\run_recipe\recipe_builder.py", line 20, in from_list
    tasks = cls.read_tasks(data)
  File "C:\Users\user\.virtualenvs\ultimate-geography-Xfb4eIRA\lib\site-packages\brain_brew\commands\run_recipe\recipe_builder.py", line 68, in read_tasks
    task_or_tasks = [matching_task.from_repr(task_arguments)]
  File "C:\Users\user\.virtualenvs\ultimate-geography-Xfb4eIRA\lib\site-packages\brain_brew\commands\run_recipe\parts_builder.py", line 40, in from_repr
    return cls.from_list(data)
  File "C:\Users\user\.virtualenvs\ultimate-geography-Xfb4eIRA\lib\site-packages\brain_brew\commands\run_recipe\recipe_builder.py", line 20, in from_list
    tasks = cls.read_tasks(data)
  File "C:\Users\user\.virtualenvs\ultimate-geography-Xfb4eIRA\lib\site-packages\brain_brew\commands\run_recipe\recipe_builder.py", line 73, in read_tasks
    inner_task.execute()
  File "C:\Users\user\.virtualenvs\ultimate-geography-Xfb4eIRA\lib\site-packages\brain_brew\build_tasks\csvs\notes_from_csvs.py", line 69, in execute
    csv_map.compile_data()
  File "C:\Users\user\.virtualenvs\ultimate-geography-Xfb4eIRA\lib\site-packages\brain_brew\transformers\file_mapping.py", line 156, in compile_data
    data_in_progress = self._build_data_recursive()
  File "C:\Users\user\.virtualenvs\ultimate-geography-Xfb4eIRA\lib\site-packages\brain_brew\transformers\file_mapping.py", line 113, in _build_data_recursive
    raise Exception(column_repeat_errors)
Exception: [KeyError('Derivative column  in multiple derivative lines')]
```
this happened when i run source to anki, after done translating. Can anybody help me?

**Comment by KnowScratcher** [comment]
wait, i think i've solved it

**Comment by KnowScratcher** [comment]
Hello, will v5.3 be released?

**Comment by KnowScratcher** [comment]
Hello, sorry to ask again but when will v5.3 be released
